### ISSUE TITLE
change_by_user for PartSet is "N/A"

### ISSUE THREAD

**Issue by crallian** [pyspcwebgw/pyspcwebgw#22]
For PartSet, change_by_user now reports "N/A".

Background:
As discussed in #4, prior to the merge of #10, there was a bug so the wrong PartSet user was reported.

As the user for last PartSet is not provided by the EDP protocol, it was decided in #10 to set PartSet user to "N/A" (instead of falsely returning the last FullSet user)

Suggestion:
It has been found that the PartSet user can be extracted from the SIA protocol instead, in the "description" section.
This can be implemented as shown in PR #11

**Comment by jschlyter** [comment]
Can we close this @crallian ?

**Comment by crallian** [comment]
> Can we close this @crallian ?

Yes, please close this issue! =)
