### ISSUE TITLE
For Si-Way connected PIRs, only zone close is reported

### ISSUE THREAD

**Issue by fredriklj** [pyspcwebgw/pyspcwebgw#3]
From what I gather pyspcwebgw only recognises ZoneInput.CLOSED for PIR sensors connected to the SPC via Si-Way. Looking at the data received on the websockets connection, this seems to be caused by the SPC system reporting both (sia_code) ZO and ZC in the same instance with the same time stamp. And last write (almost always) succeeds.

This is the point where I have to admit that I have not checked wether ZO and ZC is in the same websockets message, nor have I read the code very carefully.

Discovered this as I could not use wireless PIR's for presence detection in HASS.

**Comment by crallian** [comment]
As I understand, the sia_code and zoneID in the ws message is not used to change the state in HA, but triggers a http request for the status if the Zone. The status of the zone is then updated with the repons from the http request.
The beauty with this is that we get a well defined mode-number to act on.
I actually hava a wireless PIR too, and found that ZO and ZC are sent with two different ws messages, with the same timestamp. Of course the zone is then already closed again when the first http request arrives, and therefore "updated" to closed two times in HA.
I guess an easy workaround would be to directly set the state based on sia code. Do you think this is a problem only with ZO/ZC or for more Zone sia_codes?

**Comment by fredriklj** [comment]
I would imagine this is only a problem for ZO/ZC and in this specific situation. A special case for ZO should be enough?

**Comment by crallian** [comment]
Yes, tjats what I did, see my fork/pull request.

**Comment by fredriklj** [comment]
I tested the changes you made  to zone.py and it does work. It doesn't give the best visual feedback in hass, as it only flickers to detected and back. As opposed to a detection with a wired sensor, which holds its detected state for a second or so.

For me its not an issue. Automations based on state change of the sensor works.

**Comment by tobpet** [comment]
I also have this issue with wireless detectors.
Would be great if this issue is solved in master! I have tested crallian's fork and it solves the issue.
